jobs:
  test:
    env:
      ANDROID_HOME: /
    name: JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous runs
      uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Check out repository
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
      with:
        key: maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: 'maven-

          '
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Install
      run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        install -U -DskipTests=true -am -pl caliper
      shell: bash
    - continue-on-error: true
      name: Test
      run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        clean verify -U -Dmaven.javadoc.skip=true -am -pl caliper
      shell: bash
    strategy:
      matrix:
        java:
        - 8
        - 11
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
